language: cpp
dist: bionic
services:
    - docker

before_install:
    # Install zig
    - sudo snap install zig --classic --edge

    # Make sure zig runs
    - zig --help

script:
    # Run tests
    - zig test src/datetime.zig
